### ISSUE TITLE
Review Variants badges

### ISSUE THREAD

**Issue by mvelinder** [iobio/clin.iobio#123] opened 2020-03-13 18:14 UTC
From Al -
If I assign significance to a variant, it appears in the workflow. How many variants can be reviewed before this becomes a problem? (I only had three variants, so couldn’t assign significance to more to see what would happen)

I’m updating this comment based on the new design. I reviewed a bunch of variants, and the badges overlap the words, and the bar at the top is now starting to take up a fair bit of vertical space. Maybe it would be better to just indicate the number of significant and VUS variants, rather than giving this much detail? It is only a summary in the bar after all,
![image](https://user-images.githubusercontent.com/22081541/76648360-27d94580-6524-11ea-9c62-f7f16eeaf4cb.png)

**Comment by adityaekawade** [comment] 2020-03-20 20:22
The new update for badges on "findings" will show the count for variants reviewed as "significant", "unknown significance" and "poor quality". 

<img width="1108" alt="Screen Shot 2020-03-20 at 1 12 19 PM" src="https://user-images.githubusercontent.com/16284713/77203422-9894da80-6aad-11ea-8bad-584becbb28c1.png">

**Comment by tonydisera** [comment] 2020-03-21 15:59
I noticed that 'Poor Quality' is showing up as a badge.  Do we want this?
<img width="351" alt="Screen Shot 2020-03-21 at 9 58 17 AM" src="https://user-images.githubusercontent.com/8420103/77230554-a0f71f00-6b5a-11ea-8a50-9fdcb0a09f32.png">

**Comment by tonydisera** [comment] 2020-03-21 16:00
Also, on the Findings page, we are showing 'Poor Quality' and 'Not Reviewed' variants.  Is this new behavior?  I would vote for excluding 'Variants not Reviewed' from the Findings page.  Also, it seems like 'Poor Quality' is not a 'Finding'.

<img width="1524" alt="Screen Shot 2020-03-21 at 9 58 12 AM" src="https://user-images.githubusercontent.com/8420103/77230578-d00d9080-6b5a-11ea-8eb0-91683a18c1be.png">

**Comment by tonydisera** [comment] 2020-03-21 16:03
Should I hold off on the pull request or must merge it?  I'm not sure what do do with these kind of issues where there are open questions.  Thoughts @mvelinder @AlistairNWard ?

**Comment by AlistairNWard** [comment] 2020-03-22 23:38
Maybe this is worth a chat Monday? @tonydisera 

I agree that Not Reviewed and Poor Quality are not findings and shouldn't be included in a table in the findings page. I think it might be worth showing something on the Findings page (hence why it might be worth a chat). The findings page, in my opinion, should show a summary of the analysis. If the analysis is complete, but some variants are not reviewed, or are of low quality, we don't want to give the impression that analysis is complete. Or, if the review variants step is marked as complete, maybe we do. But maybe there should be something on the Findings page making sure this is all clear?

**Comment by tonydisera** [comment] 2020-03-23 00:31
I was mistaken.  The Findings page is showing 'Poor Quality' and 'Not significant' .  I wonder if we could have a circular chart at the top that % reviewed .

**Comment by tonydisera** [comment] 2020-03-23 00:32
I am running into an intermittent bug with this feature that looks to be timing related.  Sometimes I will mark a variant as 'significant' and then this badge shows.
<img width="1337" alt="Screen Shot 2020-03-22 at 6 30 01 PM" src="https://user-images.githubusercontent.com/8420103/77268427-7f398d00-6c6b-11ea-9830-3bcedd9d20d9.png">

**Comment by tonydisera** [comment] 2020-03-23 01:06
Good news @adityaekawade .  I think this might be something out-of-sync on dev.clin.iobio.io as I can only reproduce it there.  stage.clin.iobio doesn't seem to exhibit the same behavior.

**Comment by AlistairNWard** [comment] 2020-03-23 01:28
The badges should be capitalized. In the left menu and the Variant Review dropdown, the annotations are capitalized (e.g. Significant), but the badge is significant.

**Comment by adityaekawade** [comment] 2020-03-23 21:12
The badges in the workflow nav are all in lowercase. 
<img width="763" alt="Screen Shot 2020-03-23 at 2 02 27 PM" src="https://user-images.githubusercontent.com/16284713/77363044-3a673200-6d0f-11ea-8153-456279a6bdb7.png">

So, I will capitalize the first letter of each badge for consistency.

**Comment by AlistairNWard** [comment] 2020-03-23 22:56
Good point. Unless there are objections, I would say yes, capitalize them all

**Comment by mvelinder** [comment] 2020-03-26 13:40
I am still seeing clipping of Poor quality to a new line. I'd prefer to have the progress bar wider horizontally and keeping all 3 (Significant, Unknown significance and Poor quality) on the same line 

![image](https://user-images.githubusercontent.com/22081541/77653132-fe151b00-6f34-11ea-905d-aebe85cbb1b6.png)

**Comment by mvelinder** [comment] 2020-03-26 13:58
Also probably related to this issue, when I add a note but do not review the variant as Significant, Unknown, etc... I'm seeing a small blue bar like a badge with no text in it. We should just have it automatically assign Unknown significance and that badge here, to match the Unknown significance on the Findings page

![image](https://user-images.githubusercontent.com/22081541/77655104-96140400-6f37-11ea-83b7-e849d584cb6e.png)

**Comment by adityaekawade** [comment] 2020-03-26 14:19
Hi @mvelinder , I thought one extra line did not look bad, hence I had kept it that way.  But I can push a quick fix so that all 3 badges are horizontal. 

Blue bar issue is within the iframe, so needs to be addressed from Gene.iobio. I will add that as an issue in gene.iobio repo and fix it.

**Comment by AlistairNWard** [comment] 2020-03-26 14:43
We could easily grow the clin concept to include more steps, so increasing the space between each step may not be desirable. I'm also completely fine with the Poor Quality badge being on the second line. All in a line might look a bit weird, and I don't think the cost in vertical space is a big deal. I don't feel strongly about this, but I'm happy with how it is now

**Comment by mvelinder** [comment] 2020-03-26 15:04
If it doesn't bother anyone else we can keep it clipping to the second line. It also redraws and bumps things around slightly when it adds the new line. Let's just keep it as is then @adityaekawade

**Comment by adityaekawade** [comment] 2020-03-26 15:22
Okay. I am keeping it as it is for now, but if anything needs to be changed it should be a quick fix. 
I am moving this to "final review" since PR is merged.

**Comment by AlistairNWard** [comment] 2020-03-26 15:36
@mvelinder @adityaekawade I'm good to close this, but created a new issue #145 that we should look at

**Closed** 2020-03-27 17:08 UTC
Labels: review complete
