### ISSUE TITLE
Adding Uncertain Significance clips off the text

### ISSUE THREAD

**Issue by mvelinder** [iobio/clin.iobio#266] opened 2020-07-22 19:27 UTC
![image](https://user-images.githubusercontent.com/22081541/88219605-1533f300-cc1f-11ea-8260-e632e6c050ff.png)

**Comment by adityaekawade** [comment] 2020-07-22 20:16
This is strange. Also, there is a scroll bar added. 
<img width="315" alt="Screen Shot 2020-07-22 at 1 15 53 PM" src="https://user-images.githubusercontent.com/16284713/88224233-896d9700-cc1d-11ea-8b20-00e693674fb1.png">

**Comment by adityaekawade** [comment] 2020-07-23 23:22
@mvelinder I am not able to reproduce this issue. I tried by resizing my window as well as trying in different browsers. Do you also see this is gene.iobio or only in clin?

**Comment by mvelinder** [comment] 2020-08-03 12:03
I'm still seeing it on dev.clin

![image](https://user-images.githubusercontent.com/22081541/89180421-f6066100-d54e-11ea-8d7f-91be10a5a777.png)

@AlistairNWard can you try to reproduce this error for us?

**Comment by mvelinder** [comment] 2020-08-04 11:56
This is also happening on production gene.iobio for me @adityaekawade and @AlistairNWard 

![image](https://user-images.githubusercontent.com/22081541/89291120-2c0f1800-d617-11ea-85ee-27fdeedef03a.png)

**Comment by AlistairNWard** [comment] 2020-08-04 14:41
I can't reproduce this on production gene.iobio. You also have a thing over the "Show variants by inheritance" dropdown, but I also don't see that. I also tried resizing the window, but nothing I did could make that happen.

**Comment by AlistairNWard** [comment] 2021-02-18 16:25
Just tried this again on dev.clin, clin, and gene. Fussed with screen sizes etc. but still can't reproduce. Do you still see this @mvelinder ?

**Comment by adityaekawade** [comment] 2021-02-18 16:39
I guess this might be a Linux/ Ubuntu issue.

**Comment by adityaekawade** [comment] 2021-02-26 17:21
This doesn’t seem to be reproducible on Mac

**Comment by AlistairNWard** [comment] 2021-02-26 17:48
I can't reproduce this at all, so I think we should just close this

**Closed** 2021-02-26 19:09 UTC
Labels: review complete
